# Generated by Django 3.1.1 on 2020-10-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0001_initial_squashed_0008_auto_20200908_1450_squashed_0005_auto_20200909_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
