# Generated by Django 3.0.8 on 2020-09-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0001_player-score-migrations'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='game',
            name="Only ['Tharsis', 'Elysium', 'Hellas'] maps are allowed.",
        ),
        migrations.RemoveConstraint(
            model_name='playerscore',
            name='Only defined corporations are allowed.',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_map',
            field=models.CharField(choices=[('Tharsis', 'Tharsis'), ('Elysium', 'Elysium'), ('Hellas', 'Hellas')], default='Tharsis', max_length=16),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='corporation',
            field=models.CharField(choices=[('Aphrodite', 'Aphrodite'), ('Aridor', 'Aridor'), ('Arklight', 'Arklight'), ('Celestic', 'Celestic'), ('Cheung Shing Mars', 'Cheung Shing Mars'), ('Credicor', 'Credicor'), ('Ecoline', 'Ecoline'), ('Helion', 'Helion'), ('Interplanetary Cinematics', 'Interplanetary Cinematics'), ('Inventrix', 'Inventrix'), ('Manutech', 'Manutech'), ('Mining Guild', 'Mining Guild'), ('Morning Star Inc.', 'Morning Star Inc.'), ('Phobolog', 'Phobolog'), ('Point Luna', 'Point Luna'), ('Polyphemos', 'Polyphemos'), ('Poseidon', 'Poseidon'), ('Robinson Industries', 'Robinson Industries'), ('Saturn Systems', 'Saturn Systems'), ('Storm Craft Incorporated', 'Storm Craft Incorporated'), ('Terractor', 'Terractor'), ('Tharsis Republic', 'Tharsis Republic'), ('Thorgate', 'Thorgate'), ('United Nations Mars Initiative', 'United Nations Mars Initiative'), ('Valley Trust', 'Valley Trust'), ('Viron', 'Viron'), ('Vitor', 'Vitor')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(check=models.Q(game_map__in={'Hellas', 'Elysium', 'Tharsis'}), name="Only ['Tharsis', 'Elysium', 'Hellas'] maps are allowed."),
        ),
        migrations.AddConstraint(
            model_name='playerscore',
            constraint=models.CheckConstraint(check=models.Q(corporation__in={'Poseidon', 'Aridor', 'Vitor', 'Polyphemos', 'Cheung Shing Mars', 'Credicor', 'Celestic', 'Saturn Systems', 'United Nations Mars Initiative', 'Ecoline', 'Tharsis Republic', 'Storm Craft Incorporated', 'Valley Trust', 'Aphrodite', 'Helion', 'Manutech', 'Point Luna', 'Robinson Industries', 'Phobolog', 'Mining Guild', 'Terractor', 'Interplanetary Cinematics', 'Morning Star Inc.', 'Inventrix', 'Thorgate', 'Arklight', 'Viron'}), name='Only defined corporations are allowed.'),
        ),
    ]
