# Generated by Django 3.1.1 on 2020-09-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0001_initial_squashed_0008_auto_20200908_1450'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playerscore',
            name='Only defined corporations are allowed.',
        ),
        migrations.AddField(
            model_name='game',
            name='number_of_generations',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='corporation',
            field=models.CharField(choices=[('Aphrodite', 'Aphrodite'), ('Aridor', 'Aridor'), ('Arklight', 'Arklight'), ('Celestic', 'Celestic'), ('Cheung Shing Mars', 'Cheung Shing Mars'), ('Credicor', 'Credicor'), ('Ecoline', 'Ecoline'), ('Helion', 'Helion'), ('Interplanetary Cinematics', 'Interplanetary Cinematics'), ('Inventrix', 'Inventrix'), ('N/A', 'N/A'), ('Manutech', 'Manutech'), ('Mining Guild', 'Mining Guild'), ('Morning Star Inc.', 'Morning Star Inc.'), ('Phobolog', 'Phobolog'), ('Point Luna', 'Point Luna'), ('Polyphemos', 'Polyphemos'), ('Poseidon', 'Poseidon'), ('Robinson Industries', 'Robinson Industries'), ('Saturn Systems', 'Saturn Systems'), ('Storm Craft Incorporated', 'Storm Craft Incorporated'), ('Teractor', 'Teractor'), ('Tharsis Republic', 'Tharsis Republic'), ('Thorgate', 'Thorgate'), ('United Nations Mars Initiative', 'United Nations Mars Initiative'), ('Valley Trust', 'Valley Trust'), ('Viron', 'Viron'), ('Vitor', 'Vitor')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='playerscore',
            constraint=models.CheckConstraint(check=models.Q(corporation__in={'Aphrodite', 'Point Luna', 'Thorgate', 'Ecoline', 'Interplanetary Cinematics', 'Robinson Industries', 'Tharsis Republic', 'N/A', 'Celestic', 'Storm Craft Incorporated', 'Arklight', 'Manutech', 'United Nations Mars Initiative', 'Viron', 'Poseidon', 'Teractor', 'Vitor', 'Helion', 'Aridor', 'Cheung Shing Mars', 'Phobolog', 'Valley Trust', 'Mining Guild', 'Polyphemos', 'Credicor', 'Saturn Systems', 'Morning Star Inc.', 'Inventrix'}), name='Only defined corporations are allowed.'),
        ),
    ]
