# Generated by Django 3.0.8 on 2020-08-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0002_auto_20200802_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_map',
            field=models.CharField(choices=[('Tharsis', 'Tharsis'), ('Elysium', 'Elysium'), ('Hellas', 'Hellas')], default='Tharsis', max_length=14),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='corporation',
            field=models.CharField(choices=[('Vitor', 'Vitor'), ('Valley Trust', 'Valley Trust'), ('Viron', 'Viron'), ('United Nations Mars Initiative', 'United Nations Mars Initiative'), ('Thorgate', 'Thorgate'), ('Terractor', 'Terractor'), ('Tharsis Republic', 'Tharsis Republic'), ('Saturn Systems', 'Saturn Systems'), ('Storm Craft Incorporated', 'Storm Craft Incorporated'), ('Robinson Industries', 'Robinson Industries'), ('Poseidon', 'Poseidon'), ('Point Luna', 'Point Luna'), ('Polyphemos', 'Polyphemos'), ('Phobolog', 'Phobolog'), ('Morning Star Inc.', 'Morning Star Inc.'), ('Manutech', 'Manutech'), ('Mining Guild', 'Mining Guild'), ('Inventrix', 'Inventrix'), ('Interplanetary Cinematics', 'Interplanetary Cinematics'), ('Helion', 'Helion'), ('Ecoline', 'Ecoline'), ('Cheung Shing Mars', 'Cheung Shing Mars'), ('Credicor', 'Credicor'), ('Celestic', 'Celestic'), ('Arklight', 'Arklight'), ('Aridor', 'Aridor'), ('Aphrodite', 'Aphrodite')], max_length=40),
        ),
    ]
