# Generated by Django 3.1 on 2020-09-08 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0002_auto_20200906_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerscore',
            options={'default_related_name': 'scores'},
        ),
        migrations.RemoveConstraint(
            model_name='game',
            name="Only ['Tharsis', 'Elysium', 'Hellas'] maps are allowed.",
        ),
        migrations.AlterField(
            model_name='player',
            name='motto',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='mars_api.game'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(check=models.Q(game_map__in={'Hellas', 'Elysium', 'Tharsis'}), name="Only {'Hellas', 'Elysium', 'Tharsis'} maps are allowed."),
        ),
    ]
