# Generated by Django 3.1.1 on 2020-10-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0002_playerscore_is_winner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playerscore',
            name='Only defined corporations are allowed.',
        ),
        migrations.AddConstraint(
            model_name='playerscore',
            constraint=models.CheckConstraint(check=models.Q(corporation__in={'Arklight', 'United Nations Mars Initiative', 'Saturn Systems', 'Robinson Industries', 'Vitor', 'Credicor', 'Helion', 'N/A', 'Manutech', 'Cheung Shing Mars', 'Aphrodite', 'Poseidon', 'Viron', 'Aridor', 'Morning Star Inc.', 'Celestic', 'Valley Trust', 'Inventrix', 'Storm Craft Incorporated', 'Point Luna', 'Phobolog', 'Polyphemos', 'Tharsis Republic', 'Mining Guild', 'Thorgate', 'Interplanetary Cinematics', 'Ecoline', 'Teractor'}), name='only_defined_corporations_are_allowed'),
        ),
        migrations.AddConstraint(
            model_name='playerscore',
            constraint=models.UniqueConstraint(condition=models.Q(is_winner=True), fields=('is_winner', 'game'), name='One_winner_per_game'),
        ),
    ]
