# Generated by Django 3.0.8 on 2020-08-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0003_auto_20200824_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_scores', to='mars_api.Game'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_score', to='mars_api.Player'),
        ),
    ]
