# Generated by Django 3.1.1 on 2021-05-29 09:29

from django.db import migrations

from django.conf import settings

def create_data(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    user = User(pk=1, username="auth0user", is_active=True , email="email@email.com")
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0003_auto_20201009_1612'),
    ]

    operations = [
            migrations.RunPython(create_data),
    ]
