# Generated by Django 3.0.8 on 2020-08-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0004_auto_20200826_1559'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(check=models.Q(game_map__in=['Tharsis', 'Elysium', 'Hellas']), name="Only ['Tharsis', 'Elysium', 'Hellas'] maps are allowed."),
        ),
    ]
