# Generated by Django 3.0.8 on 2020-08-04 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0004_auto_20200804_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='mars_api.Player'),
        ),
    ]
