# Generated by Django 3.1.1 on 2021-07-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0005_playerstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='games_played',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
