# Generated by Django 3.0.8 on 2020-08-06 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0005_auto_20200804_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 12, 15, 23, 867035, tzinfo=utc)),
        ),
    ]
