# Generated by Django 3.0.8 on 2020-08-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0005_auto_20200830_1150'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playerscore',
            constraint=models.CheckConstraint(check=models.Q(corporation__in=['Aphrodite', 'Aridor', 'Arklight', 'Celestic', 'Cheung Shing Mars', 'Credicor', 'Ecoline', 'Helion', 'Interplanetary Cinematics', 'Inventrix', 'Manutech', 'Mining Guild', 'Morning Star Inc.', 'Phobolog', 'Point Luna', 'Polyphemos', 'Poseidon', 'Robinson Industries', 'Saturn Systems', 'Storm Craft Incorporated', 'Terractor', 'Tharsis Republic', 'Thorgate', 'United Nations Mars Initiative', 'Valley Trust', 'Viron', 'Vitor']), name='Only defined corporations are allowed.'),
        ),
    ]
