# Generated by Django 3.1.1 on 2021-07-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0006_auto_20210705_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='average_player_number',
            new_name='average_number_of_players_in_games',
        ),
    ]
