# Generated by Django 3.0.8 on 2020-08-10 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0006_auto_20200806_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 9, 5, 46, 309975, tzinfo=utc)),
        ),
        migrations.AddConstraint(
            model_name='playerscore',
            constraint=models.UniqueConstraint(fields=('player', 'game'), name='one_score_per_player_per_game'),
        ),
    ]
