# Generated by Django 3.0.8 on 2020-08-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0006_auto_20200830_1301'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playerscore',
            constraint=models.UniqueConstraint(fields=('corporation',), name='one_unique_corporation_per_game'),
        ),
    ]
