# Generated by Django 3.0.8 on 2020-08-11 18:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0007_auto_20200810_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 18, 11, 11, 320928, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_scores', to='mars_api.Player'),
        ),
    ]
