# Generated by Django 3.1.1 on 2021-07-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0007_auto_20210706_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
