# Generated by Django 3.0.8 on 2020-08-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_api', '0007_auto_20200830_1318'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playerscore',
            name='one_unique_corporation_per_game',
        ),
        migrations.AddConstraint(
            model_name='playerscore',
            constraint=models.UniqueConstraint(fields=('corporation', 'game'), name='one_unique_corporation_per_game'),
        ),
    ]
