  version: '3.7'
    
  services:
    db:
      image: postgres:12
      environment:
        - POSTGRES_DB=mars
        - POSTGRES_USER=martian
        - POSTGRES_PASSWORD=thorgate
    web:
      build: .
      command: daphne -b 0.0.0.0 -p 8000 mars.asgi:application
      #command: bash ./wait-for-it.sh db:5432 -- daphne -b 0.0.0.0 -p 8000 mars.asgi:application
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - db
