version: '3.7'

services:
    test-db:
      image: postgres:12
      environment:
        - POSTGRES_DB=test
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
    test-web:
      build:
          context: .
          dockerfile: Dockerfile
          args:
            POETRY_EXPORT_FLAGS: --dev
      volumes:
        - .:/app
      depends_on:
        - test-db
