[tool.poetry]
name = "terra-mars-api"
version = "0.1.0"
description = ""
authors = ["Rokas Bagdonas rokius.bagdonas@gmail.com"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.7"
psycopg2-binary = "^2.8"
djangorestframework = "^3.11.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
