# Generated by Django 3.0.8 on 2020-07-19 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('game_map', models.CharField(choices=[('THR', 'Tharsis'), ('ELS', 'Elysium'), ('HEL', 'Hellas')], max_length=10)),
                ('draft_variant', models.BooleanField(default=True)),
                ('prelude', models.BooleanField(default=False)),
                ('venus_next', models.BooleanField(default=False)),
                ('colonies', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=32, null=True)),
                ('motto', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation', models.CharField(choices=[('APH', 'Aphrodite'), ('ARD', 'Aridor'), ('ARK', 'Arklight'), ('CLS', 'Celestic'), ('CRE', 'Credicor'), ('CSM', 'Cheung Shing Mars'), ('ECO', 'Ecoline'), ('HEL', 'Helion'), ('IPC', 'Interplanetary Cinematics'), ('IVN', 'Inventrix'), ('MNG', 'Mining Guild'), ('MNT', 'Manutech'), ('MSI', 'Morning Star Inc.'), ('PBL', 'Phobolog'), ('PLP', 'Polyphemos'), ('PNL', 'Point Luna'), ('PSD', 'Poseidon'), ('RBI', 'Robinson Industries'), ('SCI', 'Storm Craft Incorporated'), ('STS', 'Saturn Systems'), ('TAR', 'Tharsis Republic'), ('TER', 'Terractor'), ('THR', 'Thorgate'), ('UMN', 'United Nations Mars Initiative'), ('VIR', 'Viron'), ('VLT', 'Valley Trust'), ('VTR', 'Vitor')], max_length=40)),
                ('terraform_rating', models.PositiveSmallIntegerField(default=20)),
                ('milestones', models.PositiveSmallIntegerField(default=0)),
                ('awards', models.PositiveSmallIntegerField(default=0)),
                ('greeneries', models.PositiveSmallIntegerField(default=0)),
                ('cities', models.PositiveSmallIntegerField(default=0)),
                ('event_cards', models.SmallIntegerField(default=0)),
                ('automated_cards', models.SmallIntegerField(default=0)),
                ('active_cards', models.SmallIntegerField(default=0)),
                ('resources', models.SmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='username', to='api.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='api.PlayerScore', to='api.Player'),
        ),
    ]
