# Generated by Django 3.0.8 on 2020-07-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number_of_players',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
