# Generated by Django 3.0.8 on 2020-07-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_number_of_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergame',
            old_name='game',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='playergame',
            old_name='player',
            new_name='player_nickname',
        ),
    ]
