# Generated by Django 3.0.8 on 2020-07-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200714_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerGame',
            new_name='PlayerScore',
        ),
    ]
